<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="GTFSRawPackages" nsURI="platform://plugin/no.ntnu.tdt4350.TransportWizard/model/GTFSRaw.ecore"
    nsPrefix="GTFSRaw">
  <eClassifiers xsi:type="ecore:EClass" name="CollectionRaw">
    <eOperations name="readGTFSFiles" lowerBound="1">
      <eParameters name="pathToFolder" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="csvCommaChar" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="readAgencyFile" lowerBound="1">
      <eParameters name="absolutePathToFile" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="csvCommaChar" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="readRoutesFile" lowerBound="1">
      <eParameters name="absolutePathToFile" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="csvCommaChar" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="readTripsFile" lowerBound="1">
      <eParameters name="absolutePathToFile" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="csvCommaChar" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="readStopTimesFile" lowerBound="1">
      <eParameters name="absolutePathToFile" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="csvCommaChar" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="readStopsFile" lowerBound="1">
      <eParameters name="absolutePathToFile" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="csvCommaChar" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="readCalendarFile" lowerBound="1">
      <eParameters name="absolutePathToFile" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="csvCommaChar" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="readOptionalFile" lowerBound="1">
      <eParameters name="absolutePathToFile" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="csvCommaChar" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="fixSubstrings" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="inputString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="csvCommaChar" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agency" upperBound="-1"
        eType="#//AgencyRaw" eKeys="#//AgencyRaw/Name #//AgencyRaw/URL #//AgencyRaw/Timezone"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes" upperBound="-1"
        eType="#//RouteRaw" eKeys="#//RouteRaw/RouteID"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trips" upperBound="-1"
        eType="#//TripRaw" eKeys="#//TripRaw/TripID"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stopTimes" upperBound="-1"
        eType="#//StopTimeRaw" eKeys="#//StopTimeRaw/StopID #//StopTimeRaw/TripID"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stops" upperBound="-1"
        eType="#//StopRaw" eKeys="#//StopRaw/StopID"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calender" upperBound="-1"
        eType="#//CalenderRaw" eKeys="#//CalenderRaw/ServiceID"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionalTable" upperBound="-1"
        eType="#//OptionalTableRaw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgencyRaw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URL" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Timezone" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Columns" upperBound="-1"
        eType="#//OptionalColumnRaw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RouteRaw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RouteID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShortName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LongName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RouteType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Columns" upperBound="-1"
        eType="#//OptionalColumnRaw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TripRaw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TripID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RouteID" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ServiceID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Columns" upperBound="-1"
        eType="#//OptionalColumnRaw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StopTimeRaw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StopID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TripID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrivalTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depatureTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopSequence" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Columns" upperBound="-1"
        eType="#//OptionalColumnRaw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StopRaw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StopID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Longitude" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Latitude" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Columns" upperBound="-1"
        eType="#//OptionalColumnRaw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalenderRaw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ServiceID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StartDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StopDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Monday" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Tuesday" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Wednesday" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Thursday" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Friday" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Saturday" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Sunday" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Columns" upperBound="-1"
        eType="#//OptionalColumnRaw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionalTableRaw">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Columns" lowerBound="1"
        upperBound="-1" eType="#//OptionalColumnRaw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionalColumnRaw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ColumnName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ColumnValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
